DROP TYPE IF EXISTS ORDER_TYPE;
DROP TYPE IF EXISTS TRADE_TYPE;
DROP TYPE IF EXISTS ORDER_STATUS_TYPE;
CREATE TYPE ORDER_TYPE AS ENUM('MARKET', 'LIMIT');
CREATE TYPE TRADE_TYPE AS ENUM('BUY', 'SELL');
CREATE TYPE ORDER_STATUS_TYPE AS ENUM('EXECUTED', 'CANCELLED','EXPIRED', 'PLACED', 'PARTIALLY_EXECUTED');


