DROP TYPE IF EXISTS ORDER_TYPE;
DROP TYPE IF EXISTS TRADE_TYPE;
DROP TYPE IF EXISTS ORDER_STATUS_TYPE;
DROP TYPE IF EXISTS RECORD_PRICE_TYPE;
DROP TYPE IF EXISTS HOLIDAY_TYPE;
CREATE TYPE ORDER_TYPE AS ENUM('MARKET', 'LIMIT');
CREATE TYPE TRADE_TYPE AS ENUM('BUY', 'SELL');
CREATE TYPE ORDER_STATUS_TYPE AS ENUM('EXECUTED', 'CANCELLED','EXPIRED', 'PLACED', 'PARTIALLY_EXECUTED');
CREATE TYPE RECORD_PRICE_TYPE AS ENUM('OPEN', 'CLOSE','HIGH', 'LOW', 'FIVE_MINUTE', 'ONE_MINUTE','HOURLY');
CREATE TYPE HOLIDAY_TYPE AS ENUM('ONCE', 'RECURRING');


